# Adversarial (GAN) Training config
trainer: gan   
seed: 42
variant: "medium"        # "low" | "medium" | "high"
scale: 2
patch_hr: 192

# Daten
lr_train: "C:\\Users\\jandw\\SRCNN\\Data\\train\\low_res_x2"
hr_train: "C:\\Users\\jandw\\SRCNN\\Data\\train\\high_res"
lr_val:   "C:\\Users\\jandw\\SRCNN\\Data\\val\\low_res_x2"
hr_val:   "C:\\Users\\jandw\\SRCNN\\Data\\val\\high_res"


# Laufzeit
batch_size: 24
workers: 4
epochs: 800
amp: true
grad_clip: 1.0
val_every: 1

# Optimizer / Scheduler
lr_g: 1.0e-4
lr_d: 1.0e-4
wd_g: 0.0
wd_d: 0.0
cosine: true
lr_min: 0.0

# Verluste
l1_weight: 1.0     # Content (L1)
adv_weight: 0.005  # Adversarial Stärke (klein halten)
use_y: false       # Y-Channel für Loss/PSNR? (false = RGB)

# Discriminator
disc_channels: 64

# I/O
out_dir: "checkpoints/medium/x2_gan"
run_name: "srcnn_gan_medium_x2"

# Resume (optional)
# resume_g: "checkpoints/gan/x4/srcnn_gan_x4_G_latest.pt"
# resume_d: "checkpoints/gan/x4/srcnn_gan_x4_D_latest.pt"
